# https://taskfile.dev

version: "3"

vars:
  ART: https://raw.githubusercontent.com/firefly-zero/firefly-art/main

tasks:
  install-deps:
    status:
      - test -f .venv/bin/python
    sources:
      - requirements.txt
    cmds:
      - python3 -m venv .venv
      - .venv/bin/pip install -r requirements.txt
  build:
    deps:
      - install-deps
    sources:
      - templates/*.j2
      - data.yaml
    generates:
      - public
    cmds:
      - mkdir -p public
      - .venv/bin/python3 generate.py

  default:
    - task: build
